version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: localhost
      MYSQL_DATABASE: social_network
      MYSQL_USER: localhost
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./your-django-app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
